services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Netlogix\Nxerrorhandler\:
    resource: '../Classes/*'

  Netlogix\Nxerrorhandler\Command\GenerateErrorPagesCommand:
    tags:
      - name: 'console.command'
        command: 'nxerrorhandler:generateErrorPages'
        description: 'Generate static error pages'
